services:
 
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./resources/migration:/usr/src/app/resources/migration
    command: ["-path", "/usr/src/app/resources/migration", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable", "up"]

  server:
    build: .
    env_file:
      - .env
    environment:
      - ADDRESS=${ADDRESS}
      - DATABASE_DSN=${DATABASE_DSN}
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: go run cmd/confidant_server/main.go

volumes:
  postgres-data: