name: Auto Increase Patch Version

on:
  push:
    branches:
      - '*' # Любая ветка
    tags-ignore:
      - 'v*.*.*' # Игнорируем пушинги самих тэгов

jobs:
  increase_patch_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest Tag
        id: get_latest_tag
        shell: bash
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 --match='v*')
          echo "::set-output name=LATEST_TAG::$LATEST_TAG"

      - name: Increment Patch Version
        id: increment_version
        shell: bash
        run: |
          LATEST_TAG="${{ steps.get_latest_tag.outputs.LATEST_TAG }}"
          VERSION_PARTS=(${LATEST_TAG/v./ })
          NEW_PATCH_VERSION=$((VERSION_PARTS[2] + 1)) # Увеличиваем только PATCH
          NEW_MINOR_VERSION=${VERSION_PARTS[1]}
          NEW_MAJOR_VERSION=${VERSION_PARTS[0]}

          NEW_TAG="v${NEW_MAJOR_VERSION}.${NEW_MINOR_VERSION}.${NEW_PATCH_VERSION}"
          echo "::set-output name=NEXT_TAG::$NEW_TAG"

      - name: Create New Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEXT_TAG="${{ steps.increment_version.outputs.NEXT_TAG }}"
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@users.noreply.github.com"
          git tag "$NEXT_TAG"
          git push origin "$NEXT_TAG"