name: Auto Increase Patch Version

on:
  push:
    branches:
      - '*' # Любая ветка
    tags-ignore:
      - 'v*.*.*' # Игнорируем пушинги самих тэгов

jobs:
  increase_patch_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest Tag
        id: get_latest_tag
        shell: bash
        run: |
          PREVIOUS_COMMIT_HASH=$(git rev-parse HEAD^)
          LATEST_TAG=$(git tag --points-at $PREVIOUS_COMMIT_HASH)
          if [[ "$LATEST_TAG" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            NEW_MAJOR_VERSION=${BASH_REMATCH[1]}
            NEW_MINOR_VERSION=${BASH_REMATCH[2]}
            NEW_PATCH_VERSION=$((BASH_REMATCH[3] + 1))
          fi
          NEW_TAG="v${NEW_MAJOR_VERSION}.${NEW_MINOR_VERSION}.${NEW_PATCH_VERSION}"
          echo "::set-output name=NEXT_TAG::$NEW_TAG"

      - name: Create New Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEXT_TAG="${{ steps.prev_commit_hash.outputs.NEXT_TAG }}"
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@users.noreply.github.com"
          git tag "$NEXT_TAG"
          git push origin "$NEXT_TAG"